---
- name: Copy root my.cnf
  template:
    src: templates/root-my.cnf.j2
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0644
  notify: Restart Mariadb

- name: Set MariaDB root password
  mysql_user:
    name: root
    password: "{{ sql_root_password }}"
    state: present
    host: localhost

- name: Remove anonymous user
  mysql_user:
    name: ''
    state: absent

- name: Remove test database
  mysql_db:
    name: test
    state: absent

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: "{{ sql_user }}"
    password: "{{ sql_user_password }}"
    priv: 'medshakeehr.*:ALL,GRANT'
    state: present

- name: Ensure MedShakeEHR database is present
  mysql_db:
    name: "{{ sql_database }}"
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Custom mysql
  template:
    src: templates/custom.cnf.j2
    dest: "/etc/mysql/mariadb.conf.d/custom.cnf"
    owner: root
    group: root
    mode: 0644
  notify: Restart Mariadb