---
- name: Setup php.ini configuration.
  template:
    src: templates/30-custom-php.ini.j2
    dest: "/etc/php/{{ php_default_version_debian }}/apache2/conf.d/30-custom-php.ini"
    owner: root
    group: root
    mode: 0644
  notify: Restart Apache
