---
- name: Set ServerTokens Prod
  lineinfile:
    path: /etc/apache2/conf-available/security.conf
    regexp: '^ServerTokens OS'
    line: ServerTokens Prod
    state: present
- name: Set ServerSignature Off
  lineinfile:
    path: /etc/apache2/conf-available/security.conf
    regexp: '^ServerSignature On'
    line: ServerSignature Off
    state: present
