---
- name: Install geerlingguy.apache role 
  community.general.ansible_galaxy_install:
    type: role
    name: geerlingguy.apache

- name: Install Apache
  include_role:
    name: geerlingguy.apache

    