---
- name: Setup orthanc configuration.
  template:
    src: templates/orthanc.conf.j2
    dest: "/etc/orthanc/orthanc.json"
    owner: root
    group: root
    mode: 0644
  when: "'orthanc' in ansible_facts.packages"