---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Include MedShakeEHR Role"
      ansible.builtin.include_role:
        name: ansible-role-medshakeehr
        
