---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: msehr-role-bookworm
    image: images:debian/bookworm/cloud
    memory: 512
    cpus: 1
  
  - name: msehr-role-trixie
    image: images:debian/trixie/cloud
    memory: 512
    cpus: 1

  - name: msehr-role-jammy
    image: images:ubuntu/jammy/cloud
    memory: 1024
    cpus: 1

  - name: msehr-role-noble
    image: images:ubuntu/noble/cloud
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier: 
  name: ansible
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
lint: |
  set -e
  yamllint .
  ansible-lint .
